version: '3.8'

services:
  # Service PHP/Apache
  app:
    build: .
    container_name: ecoride-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=ecoride_covoiturage
      - DB_USER=root
      - DB_PASSWORD=root_password
      - APP_DEBUG=true
    networks:
      - ecoride-network

  # Service MySQL
  db:
    image: mysql:8.0
    container_name: ecoride-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ecoride_covoiturage
    volumes:
      - mysql_data:/var/lib/mysql
      - ./datas/ecoride.sql:/docker-entrypoint-initdb.d/ecoride.sql
    networks:
      - ecoride-network

  # Service phpMyAdmin (optionnel)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - ecoride-network

volumes:
  mysql_data:

networks:
  ecoride-network:
    driver: bridge
